// Generated by gencpp from file niryo_robot_tools_commander/ToolAction.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_TOOLS_COMMANDER_MESSAGE_TOOLACTION_H
#define NIRYO_ROBOT_TOOLS_COMMANDER_MESSAGE_TOOLACTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_tools_commander/ToolActionGoal.h>
#include <niryo_robot_tools_commander/ToolActionResult.h>
#include <niryo_robot_tools_commander/ToolActionFeedback.h>

namespace niryo_robot_tools_commander
{
template <class ContainerAllocator>
struct ToolAction_
{
  typedef ToolAction_<ContainerAllocator> Type;

  ToolAction_()
    : action_goal()
    , action_result()
    , action_feedback()  {
    }
  ToolAction_(const ContainerAllocator& _alloc)
    : action_goal(_alloc)
    , action_result(_alloc)
    , action_feedback(_alloc)  {
  (void)_alloc;
    }



   typedef  ::niryo_robot_tools_commander::ToolActionGoal_<ContainerAllocator>  _action_goal_type;
  _action_goal_type action_goal;

   typedef  ::niryo_robot_tools_commander::ToolActionResult_<ContainerAllocator>  _action_result_type;
  _action_result_type action_result;

   typedef  ::niryo_robot_tools_commander::ToolActionFeedback_<ContainerAllocator>  _action_feedback_type;
  _action_feedback_type action_feedback;





  typedef boost::shared_ptr< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> const> ConstPtr;

}; // struct ToolAction_

typedef ::niryo_robot_tools_commander::ToolAction_<std::allocator<void> > ToolAction;

typedef boost::shared_ptr< ::niryo_robot_tools_commander::ToolAction > ToolActionPtr;
typedef boost::shared_ptr< ::niryo_robot_tools_commander::ToolAction const> ToolActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator1> & lhs, const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator2> & rhs)
{
  return lhs.action_goal == rhs.action_goal &&
    lhs.action_result == rhs.action_result &&
    lhs.action_feedback == rhs.action_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator1> & lhs, const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_tools_commander

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b925128aeeb548783d6a0f80113dd269";
  }

  static const char* value(const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb925128aeeb54878ULL;
  static const uint64_t static_value2 = 0x3d6a0f80113dd269ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_tools_commander/ToolAction";
  }

  static const char* value(const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"ToolActionGoal action_goal\n"
"ToolActionResult action_result\n"
"ToolActionFeedback action_feedback\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_tools_commander/ToolActionGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"ToolGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_tools_commander/ToolGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# goal\n"
"niryo_robot_tools_commander/ToolCommand cmd\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_tools_commander/ToolCommand\n"
"# Gripper\n"
"int8 OPEN_GRIPPER = 1\n"
"int8 CLOSE_GRIPPER = 2\n"
"\n"
"# Vacuump pump\n"
"int8 PULL_AIR_VACUUM_PUMP = 10\n"
"int8 PUSH_AIR_VACUUM_PUMP = 11\n"
"\n"
"# Tools controlled by digital I/Os\n"
"int8 SETUP_DIGITAL_IO = 20\n"
"int8 ACTIVATE_DIGITAL_IO = 21\n"
"int8 DEACTIVATE_DIGITAL_IO = 22\n"
"\n"
"uint8 cmd_type\n"
"\n"
"# Gripper1= 11, Gripper2=12, Gripper3=13, VaccuumPump=31, Electromagnet=30\n"
"int8 tool_id\n"
"\n"
"# if gripper Ned1/One\n"
"uint16 speed\n"
"\n"
"# if gripper Ned2\n"
"uint8 max_torque_percentage\n"
"uint8 hold_torque_percentage\n"
"\n"
"# if vacuum pump or electromagnet grove\n"
"bool activate\n"
"\n"
"# if tool is set by digital outputs (electromagnet)\n"
"string gpio\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_tools_commander/ToolActionResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ToolResult result\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalStatus\n"
"GoalID goal_id\n"
"uint8 status\n"
"uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n"
"uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n"
"uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n"
"                            #   and has since completed its execution (Terminal State)\n"
"uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n"
"uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n"
"                            #    to some failure (Terminal State)\n"
"uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n"
"                            #    because the goal was unattainable or invalid (Terminal State)\n"
"uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n"
"                            #    and has not yet completed execution\n"
"uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n"
"                            #    but the action server has not yet confirmed that the goal is canceled\n"
"uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n"
"                            #    and was successfully cancelled (Terminal State)\n"
"uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n"
"                            #    sent over the wire by an action server\n"
"\n"
"#Allow for the user to associate a string with GoalStatus for debugging\n"
"string text\n"
"\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_tools_commander/ToolResult\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"int32 status\n"
"string message\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_tools_commander/ToolActionFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalStatus status\n"
"ToolFeedback feedback\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_tools_commander/ToolFeedback\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# feedback\n"
"int32 progression\n"
"\n"
;
  }

  static const char* value(const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_goal);
      stream.next(m.action_result);
      stream.next(m.action_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ToolAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_tools_commander::ToolAction_<ContainerAllocator>& v)
  {
    s << indent << "action_goal: ";
    s << std::endl;
    Printer< ::niryo_robot_tools_commander::ToolActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
    s << std::endl;
    Printer< ::niryo_robot_tools_commander::ToolActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
    s << std::endl;
    Printer< ::niryo_robot_tools_commander::ToolActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_TOOLS_COMMANDER_MESSAGE_TOOLACTION_H
