arm_controller:
  type: position_controllers/JointTrajectoryController
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.0
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6

  pid_gains:
    joint_1: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }

    joint_2: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }

    joint_3: { p: 18000, d: 50, i: 0.01, i_clamp: 1 }

    joint_4: { p: 18000, d: 70, i: 0.01, i_clamp: 10000 }

    joint_5: { p: 12000, d: 70, i: 0.01, i_clamp: 1 }

    joint_6: { p: 7000, d: 50, i: 0.01, i_clamp: 1 }
