// Generated by gencpp from file niryo_robot_arm_commander/GetTrajectory.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETTRAJECTORY_H
#define NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETTRAJECTORY_H

#include <ros/service_traits.h>


#include <niryo_robot_arm_commander/GetTrajectoryRequest.h>
#include <niryo_robot_arm_commander/GetTrajectoryResponse.h>


namespace niryo_robot_arm_commander
{

struct GetTrajectory
{

typedef GetTrajectoryRequest Request;
typedef GetTrajectoryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTrajectory
} // namespace niryo_robot_arm_commander


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_arm_commander::GetTrajectory > {
  static const char* value()
  {
    return "0c4d437fb09c429b98b4c970eb404814";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetTrajectory&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_arm_commander::GetTrajectory > {
  static const char* value()
  {
    return "niryo_robot_arm_commander/GetTrajectory";
  }

  static const char* value(const ::niryo_robot_arm_commander::GetTrajectory&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_arm_commander::GetTrajectoryRequest> should match
// service_traits::MD5Sum< ::niryo_robot_arm_commander::GetTrajectory >
template<>
struct MD5Sum< ::niryo_robot_arm_commander::GetTrajectoryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_arm_commander::GetTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_arm_commander::GetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_arm_commander::GetTrajectoryRequest> should match
// service_traits::DataType< ::niryo_robot_arm_commander::GetTrajectory >
template<>
struct DataType< ::niryo_robot_arm_commander::GetTrajectoryRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_arm_commander::GetTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_arm_commander::GetTrajectoryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_arm_commander::GetTrajectoryResponse> should match
// service_traits::MD5Sum< ::niryo_robot_arm_commander::GetTrajectory >
template<>
struct MD5Sum< ::niryo_robot_arm_commander::GetTrajectoryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_arm_commander::GetTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_arm_commander::GetTrajectoryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_arm_commander::GetTrajectoryResponse> should match
// service_traits::DataType< ::niryo_robot_arm_commander::GetTrajectory >
template<>
struct DataType< ::niryo_robot_arm_commander::GetTrajectoryResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_arm_commander::GetTrajectory >::value();
  }
  static const char* value(const ::niryo_robot_arm_commander::GetTrajectoryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_ARM_COMMANDER_MESSAGE_GETTRAJECTORY_H
