// Generated by gencpp from file niryo_robot_rpi/SetAnalogIO.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_RPI_MESSAGE_SETANALOGIO_H
#define NIRYO_ROBOT_RPI_MESSAGE_SETANALOGIO_H

#include <ros/service_traits.h>


#include <niryo_robot_rpi/SetAnalogIORequest.h>
#include <niryo_robot_rpi/SetAnalogIOResponse.h>


namespace niryo_robot_rpi
{

struct SetAnalogIO
{

typedef SetAnalogIORequest Request;
typedef SetAnalogIOResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAnalogIO
} // namespace niryo_robot_rpi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_rpi::SetAnalogIO > {
  static const char* value()
  {
    return "c3eb179d3143b44ef971b15a3fa11bb0";
  }

  static const char* value(const ::niryo_robot_rpi::SetAnalogIO&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_rpi::SetAnalogIO > {
  static const char* value()
  {
    return "niryo_robot_rpi/SetAnalogIO";
  }

  static const char* value(const ::niryo_robot_rpi::SetAnalogIO&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_rpi::SetAnalogIORequest> should match
// service_traits::MD5Sum< ::niryo_robot_rpi::SetAnalogIO >
template<>
struct MD5Sum< ::niryo_robot_rpi::SetAnalogIORequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_rpi::SetAnalogIO >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetAnalogIORequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_rpi::SetAnalogIORequest> should match
// service_traits::DataType< ::niryo_robot_rpi::SetAnalogIO >
template<>
struct DataType< ::niryo_robot_rpi::SetAnalogIORequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_rpi::SetAnalogIO >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetAnalogIORequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_rpi::SetAnalogIOResponse> should match
// service_traits::MD5Sum< ::niryo_robot_rpi::SetAnalogIO >
template<>
struct MD5Sum< ::niryo_robot_rpi::SetAnalogIOResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_rpi::SetAnalogIO >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetAnalogIOResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_rpi::SetAnalogIOResponse> should match
// service_traits::DataType< ::niryo_robot_rpi::SetAnalogIO >
template<>
struct DataType< ::niryo_robot_rpi::SetAnalogIOResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_rpi::SetAnalogIO >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetAnalogIOResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_RPI_MESSAGE_SETANALOGIO_H
