// Generated by gencpp from file niryo_robot_rpi/SetPullup.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_RPI_MESSAGE_SETPULLUP_H
#define NIRYO_ROBOT_RPI_MESSAGE_SETPULLUP_H

#include <ros/service_traits.h>


#include <niryo_robot_rpi/SetPullupRequest.h>
#include <niryo_robot_rpi/SetPullupResponse.h>


namespace niryo_robot_rpi
{

struct SetPullup
{

typedef SetPullupRequest Request;
typedef SetPullupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPullup
} // namespace niryo_robot_rpi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_rpi::SetPullup > {
  static const char* value()
  {
    return "d13517c619d7e12dd61126d0d18d4c6b";
  }

  static const char* value(const ::niryo_robot_rpi::SetPullup&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_rpi::SetPullup > {
  static const char* value()
  {
    return "niryo_robot_rpi/SetPullup";
  }

  static const char* value(const ::niryo_robot_rpi::SetPullup&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_rpi::SetPullupRequest> should match
// service_traits::MD5Sum< ::niryo_robot_rpi::SetPullup >
template<>
struct MD5Sum< ::niryo_robot_rpi::SetPullupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_rpi::SetPullup >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetPullupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_rpi::SetPullupRequest> should match
// service_traits::DataType< ::niryo_robot_rpi::SetPullup >
template<>
struct DataType< ::niryo_robot_rpi::SetPullupRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_rpi::SetPullup >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetPullupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_rpi::SetPullupResponse> should match
// service_traits::MD5Sum< ::niryo_robot_rpi::SetPullup >
template<>
struct MD5Sum< ::niryo_robot_rpi::SetPullupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_rpi::SetPullup >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetPullupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_rpi::SetPullupResponse> should match
// service_traits::DataType< ::niryo_robot_rpi::SetPullup >
template<>
struct DataType< ::niryo_robot_rpi::SetPullupResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_rpi::SetPullup >::value();
  }
  static const char* value(const ::niryo_robot_rpi::SetPullupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_RPI_MESSAGE_SETPULLUP_H
