// Generated by gencpp from file niryo_robot_vision/VisualizationResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_VISION_MESSAGE_VISUALIZATIONRESPONSE_H
#define NIRYO_ROBOT_VISION_MESSAGE_VISUALIZATIONRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_vision
{
template <class ContainerAllocator>
struct VisualizationResponse_
{
  typedef VisualizationResponse_<ContainerAllocator> Type;

  VisualizationResponse_()
    : status(0)  {
    }
  VisualizationResponse_(const ContainerAllocator& _alloc)
    : status(0)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct VisualizationResponse_

typedef ::niryo_robot_vision::VisualizationResponse_<std::allocator<void> > VisualizationResponse;

typedef boost::shared_ptr< ::niryo_robot_vision::VisualizationResponse > VisualizationResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_vision::VisualizationResponse const> VisualizationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "86791dcf1de997ec7de5a0de7e4dcfcc";
  }

  static const char* value(const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x86791dcf1de997ecULL;
  static const uint64_t static_value2 = 0x7de5a0de7e4dcfccULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_vision/VisualizationResponse";
  }

  static const char* value(const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"\n"
;
  }

  static const char* value(const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualizationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_vision::VisualizationResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_VISION_MESSAGE_VISUALIZATIONRESPONSE_H
