// Generated by gencpp from file niryo_robot_msgs/Ping.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_MSGS_MESSAGE_PING_H
#define NIRYO_ROBOT_MSGS_MESSAGE_PING_H

#include <ros/service_traits.h>


#include <niryo_robot_msgs/PingRequest.h>
#include <niryo_robot_msgs/PingResponse.h>


namespace niryo_robot_msgs
{

struct Ping
{

typedef PingRequest Request;
typedef PingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Ping
} // namespace niryo_robot_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_msgs::Ping > {
  static const char* value()
  {
    return "a02bbd4704518df654c6d45037dfc59f";
  }

  static const char* value(const ::niryo_robot_msgs::Ping&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_msgs::Ping > {
  static const char* value()
  {
    return "niryo_robot_msgs/Ping";
  }

  static const char* value(const ::niryo_robot_msgs::Ping&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_msgs::PingRequest> should match
// service_traits::MD5Sum< ::niryo_robot_msgs::Ping >
template<>
struct MD5Sum< ::niryo_robot_msgs::PingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_msgs::Ping >::value();
  }
  static const char* value(const ::niryo_robot_msgs::PingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_msgs::PingRequest> should match
// service_traits::DataType< ::niryo_robot_msgs::Ping >
template<>
struct DataType< ::niryo_robot_msgs::PingRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_msgs::Ping >::value();
  }
  static const char* value(const ::niryo_robot_msgs::PingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_msgs::PingResponse> should match
// service_traits::MD5Sum< ::niryo_robot_msgs::Ping >
template<>
struct MD5Sum< ::niryo_robot_msgs::PingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_msgs::Ping >::value();
  }
  static const char* value(const ::niryo_robot_msgs::PingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_msgs::PingResponse> should match
// service_traits::DataType< ::niryo_robot_msgs::Ping >
template<>
struct DataType< ::niryo_robot_msgs::PingResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_msgs::Ping >::value();
  }
  static const char* value(const ::niryo_robot_msgs::PingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_MSGS_MESSAGE_PING_H
