(cl:defpackage niryo_robot_reports-srv
  (:use )
  (:export
   "CHECKCONNECTION"
   "<CHECKCONNECTION-REQUEST>"
   "CHECKCONNECTION-REQUEST"
   "<CHECKCONNECTION-RESPONSE>"
   "CHECKCONNECTION-RESPONSE"
   "RUNAUTODIAGNOSIS"
   "<RUNAUTODIAGNOSIS-REQUEST>"
   "RUNAUTODIAGNOSIS-REQUEST"
   "<RUNAUTODIAGNOSIS-RESPONSE>"
   "RUNAUTODIAGNOSIS-RESPONSE"
  ))

