(cl:defpackage niryo_robot_system_api_client-srv
  (:use )
  (:export
   "MANAGEETHERNET"
   "<MANAGEETHERNET-REQUEST>"
   "MANAGEETHERNET-REQUEST"
   "<MANAGEETHERNET-RESPONSE>"
   "MANAGEETHERNET-RESPONSE"
   "MANAGEWIFI"
   "<MANAGEWIFI-REQUEST>"
   "MANAGEWIFI-REQUEST"
   "<MANAGEWIFI-RESPONSE>"
   "MANAGEWIFI-RESPONSE"
  ))

