// Generated by gencpp from file niryo_robot_poses_handlers/GetTargetPoseRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETTARGETPOSEREQUEST_H
#define NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETTARGETPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace niryo_robot_poses_handlers
{
template <class ContainerAllocator>
struct GetTargetPoseRequest_
{
  typedef GetTargetPoseRequest_<ContainerAllocator> Type;

  GetTargetPoseRequest_()
    : workspace()
    , height_offset(0.0)
    , x_rel(0.0)
    , y_rel(0.0)
    , yaw_rel(0.0)  {
    }
  GetTargetPoseRequest_(const ContainerAllocator& _alloc)
    : workspace(_alloc)
    , height_offset(0.0)
    , x_rel(0.0)
    , y_rel(0.0)
    , yaw_rel(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _workspace_type;
  _workspace_type workspace;

   typedef float _height_offset_type;
  _height_offset_type height_offset;

   typedef float _x_rel_type;
  _x_rel_type x_rel;

   typedef float _y_rel_type;
  _y_rel_type y_rel;

   typedef float _yaw_rel_type;
  _yaw_rel_type yaw_rel;





  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTargetPoseRequest_

typedef ::niryo_robot_poses_handlers::GetTargetPoseRequest_<std::allocator<void> > GetTargetPoseRequest;

typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTargetPoseRequest > GetTargetPoseRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTargetPoseRequest const> GetTargetPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.workspace == rhs.workspace &&
    lhs.height_offset == rhs.height_offset &&
    lhs.x_rel == rhs.x_rel &&
    lhs.y_rel == rhs.y_rel &&
    lhs.yaw_rel == rhs.yaw_rel;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_poses_handlers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66dd79e6ec965fd249546ec36952c7f5";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66dd79e6ec965fd2ULL;
  static const uint64_t static_value2 = 0x49546ec36952c7f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_poses_handlers/GetTargetPoseRequest";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string workspace\n"
"float32 height_offset\n"
"float32 x_rel\n"
"float32 y_rel\n"
"float32 yaw_rel\n"
;
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.workspace);
      stream.next(m.height_offset);
      stream.next(m.x_rel);
      stream.next(m.y_rel);
      stream.next(m.yaw_rel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTargetPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_poses_handlers::GetTargetPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "workspace: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.workspace);
    s << indent << "height_offset: ";
    Printer<float>::stream(s, indent + "  ", v.height_offset);
    s << indent << "x_rel: ";
    Printer<float>::stream(s, indent + "  ", v.x_rel);
    s << indent << "y_rel: ";
    Printer<float>::stream(s, indent + "  ", v.y_rel);
    s << indent << "yaw_rel: ";
    Printer<float>::stream(s, indent + "  ", v.yaw_rel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETTARGETPOSEREQUEST_H
