// Generated by gencpp from file niryo_robot_poses_handlers/GetTransformPoseRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETTRANSFORMPOSEREQUEST_H
#define NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETTRANSFORMPOSEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <niryo_robot_msgs/RPY.h>

namespace niryo_robot_poses_handlers
{
template <class ContainerAllocator>
struct GetTransformPoseRequest_
{
  typedef GetTransformPoseRequest_<ContainerAllocator> Type;

  GetTransformPoseRequest_()
    : source_frame()
    , local_frame()
    , position()
    , rpy()  {
    }
  GetTransformPoseRequest_(const ContainerAllocator& _alloc)
    : source_frame(_alloc)
    , local_frame(_alloc)
    , position(_alloc)
    , rpy(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _source_frame_type;
  _source_frame_type source_frame;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _local_frame_type;
  _local_frame_type local_frame;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::niryo_robot_msgs::RPY_<ContainerAllocator>  _rpy_type;
  _rpy_type rpy;





  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetTransformPoseRequest_

typedef ::niryo_robot_poses_handlers::GetTransformPoseRequest_<std::allocator<void> > GetTransformPoseRequest;

typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTransformPoseRequest > GetTransformPoseRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetTransformPoseRequest const> GetTransformPoseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.source_frame == rhs.source_frame &&
    lhs.local_frame == rhs.local_frame &&
    lhs.position == rhs.position &&
    lhs.rpy == rhs.rpy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_poses_handlers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "920e4aacae2ebd2811d6ebb594f62a7b";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x920e4aacae2ebd28ULL;
  static const uint64_t static_value2 = 0x11d6ebb594f62a7bULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_poses_handlers/GetTransformPoseRequest";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string source_frame\n"
"string local_frame\n"
"\n"
"geometry_msgs/Point position\n"
"niryo_robot_msgs/RPY rpy\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_msgs/RPY\n"
"# roll, pitch and yaw\n"
"\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source_frame);
      stream.next(m.local_frame);
      stream.next(m.position);
      stream.next(m.rpy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTransformPoseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_poses_handlers::GetTransformPoseRequest_<ContainerAllocator>& v)
  {
    s << indent << "source_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.source_frame);
    s << indent << "local_frame: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.local_frame);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "rpy: ";
    s << std::endl;
    Printer< ::niryo_robot_msgs::RPY_<ContainerAllocator> >::stream(s, indent + "  ", v.rpy);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETTRANSFORMPOSEREQUEST_H
