// Generated by gencpp from file niryo_robot_poses_handlers/GetWorkspaceMatrixPosesResponse.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETWORKSPACEMATRIXPOSESRESPONSE_H
#define NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETWORKSPACEMATRIXPOSESRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Quaternion.h>

namespace niryo_robot_poses_handlers
{
template <class ContainerAllocator>
struct GetWorkspaceMatrixPosesResponse_
{
  typedef GetWorkspaceMatrixPosesResponse_<ContainerAllocator> Type;

  GetWorkspaceMatrixPosesResponse_()
    : status(0)
    , message()
    , matrix_position()
    , matrix_orientation()  {
    }
  GetWorkspaceMatrixPosesResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)
    , matrix_position(_alloc)
    , matrix_orientation(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _matrix_position_type;
  _matrix_position_type matrix_position;

   typedef std::vector< ::geometry_msgs::Quaternion_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Quaternion_<ContainerAllocator> >> _matrix_orientation_type;
  _matrix_orientation_type matrix_orientation;





  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetWorkspaceMatrixPosesResponse_

typedef ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<std::allocator<void> > GetWorkspaceMatrixPosesResponse;

typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse > GetWorkspaceMatrixPosesResponsePtr;
typedef boost::shared_ptr< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse const> GetWorkspaceMatrixPosesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message &&
    lhs.matrix_position == rhs.matrix_position &&
    lhs.matrix_orientation == rhs.matrix_orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_poses_handlers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73713adb73dd0b9ca6ccaa123c6a8229";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73713adb73dd0b9cULL;
  static const uint64_t static_value2 = 0xa6ccaa123c6a8229ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_poses_handlers/GetWorkspaceMatrixPosesResponse";
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string message\n"
"geometry_msgs/Point[] matrix_position\n"
"geometry_msgs/Quaternion[] matrix_orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
      stream.next(m.matrix_position);
      stream.next(m.matrix_orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetWorkspaceMatrixPosesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_poses_handlers::GetWorkspaceMatrixPosesResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "matrix_position[]" << std::endl;
    for (size_t i = 0; i < v.matrix_position.size(); ++i)
    {
      s << indent << "  matrix_position[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.matrix_position[i]);
    }
    s << indent << "matrix_orientation[]" << std::endl;
    for (size_t i = 0; i < v.matrix_orientation.size(); ++i)
    {
      s << indent << "  matrix_orientation[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "    ", v.matrix_orientation[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_GETWORKSPACEMATRIXPOSESRESPONSE_H
