// Generated by gencpp from file niryo_robot_poses_handlers/ManageDynamicFrameRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGEDYNAMICFRAMEREQUEST_H
#define NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGEDYNAMICFRAMEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_poses_handlers/DynamicFrame.h>

namespace niryo_robot_poses_handlers
{
template <class ContainerAllocator>
struct ManageDynamicFrameRequest_
{
  typedef ManageDynamicFrameRequest_<ContainerAllocator> Type;

  ManageDynamicFrameRequest_()
    : cmd(0)
    , dynamic_frame()  {
    }
  ManageDynamicFrameRequest_(const ContainerAllocator& _alloc)
    : cmd(0)
    , dynamic_frame(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _cmd_type;
  _cmd_type cmd;

   typedef  ::niryo_robot_poses_handlers::DynamicFrame_<ContainerAllocator>  _dynamic_frame_type;
  _dynamic_frame_type dynamic_frame;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(SAVE)
  #undef SAVE
#endif
#if defined(_WIN32) && defined(SAVE_WITH_POINTS)
  #undef SAVE_WITH_POINTS
#endif
#if defined(_WIN32) && defined(EDIT)
  #undef EDIT
#endif
#if defined(_WIN32) && defined(DELETE)
  #undef DELETE
#endif

  enum {
    SAVE = 1,
    SAVE_WITH_POINTS = 2,
    EDIT = 3,
    DELETE = -1,
  };


  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ManageDynamicFrameRequest_

typedef ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<std::allocator<void> > ManageDynamicFrameRequest;

typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest > ManageDynamicFrameRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest const> ManageDynamicFrameRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.dynamic_frame == rhs.dynamic_frame;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_poses_handlers

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "194e43f959f6af7862f5bdb48d9859f0";
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x194e43f959f6af78ULL;
  static const uint64_t static_value2 = 0x62f5bdb48d9859f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_poses_handlers/ManageDynamicFrameRequest";
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 SAVE = 1\n"
"int32 SAVE_WITH_POINTS = 2\n"
"int32 EDIT = 3\n"
"int32 DELETE = -1\n"
"\n"
"int32 cmd\n"
"\n"
"niryo_robot_poses_handlers/DynamicFrame dynamic_frame\n"
"\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_poses_handlers/DynamicFrame\n"
"string name # maximum lenght of dynamic_frame's name is 30 characters\n"
"string new_name\n"
"string description\n"
"bool belong_to_workspace\n"
"\n"
"geometry_msgs/Point position\n"
"niryo_robot_msgs/RPY rpy\n"
"geometry_msgs/Quaternion orientation\n"
"\n"
"geometry_msgs/Point[] points\n"
"niryo_robot_msgs/RobotState[] poses\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_msgs/RPY\n"
"# roll, pitch and yaw\n"
"\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_msgs/RobotState\n"
"geometry_msgs/Point position\n"
"niryo_robot_msgs/RPY rpy\n"
"geometry_msgs/Quaternion orientation\n"
"\n"
"geometry_msgs/Twist twist\n"
"float64 tcp_speed\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.dynamic_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageDynamicFrameRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_poses_handlers::ManageDynamicFrameRequest_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "dynamic_frame: ";
    s << std::endl;
    Printer< ::niryo_robot_poses_handlers::DynamicFrame_<ContainerAllocator> >::stream(s, indent + "  ", v.dynamic_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_POSES_HANDLERS_MESSAGE_MANAGEDYNAMICFRAMEREQUEST_H
