// Generated by gencpp from file ttl_driver/ReadVelocityProfileResponse.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_READVELOCITYPROFILERESPONSE_H
#define TTL_DRIVER_MESSAGE_READVELOCITYPROFILERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ttl_driver
{
template <class ContainerAllocator>
struct ReadVelocityProfileResponse_
{
  typedef ReadVelocityProfileResponse_<ContainerAllocator> Type;

  ReadVelocityProfileResponse_()
    : v_start(0.0)
    , a_1(0.0)
    , v_1(0.0)
    , a_max(0.0)
    , v_max(0.0)
    , d_max(0.0)
    , d_1(0.0)
    , v_stop(0.0)
    , status(0)
    , message()  {
    }
  ReadVelocityProfileResponse_(const ContainerAllocator& _alloc)
    : v_start(0.0)
    , a_1(0.0)
    , v_1(0.0)
    , a_max(0.0)
    , v_max(0.0)
    , d_max(0.0)
    , d_1(0.0)
    , v_stop(0.0)
    , status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef double _v_start_type;
  _v_start_type v_start;

   typedef double _a_1_type;
  _a_1_type a_1;

   typedef double _v_1_type;
  _v_1_type v_1;

   typedef double _a_max_type;
  _a_max_type a_max;

   typedef double _v_max_type;
  _v_max_type v_max;

   typedef double _d_max_type;
  _d_max_type d_max;

   typedef double _d_1_type;
  _d_1_type d_1;

   typedef double _v_stop_type;
  _v_stop_type v_stop;

   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReadVelocityProfileResponse_

typedef ::ttl_driver::ReadVelocityProfileResponse_<std::allocator<void> > ReadVelocityProfileResponse;

typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse > ReadVelocityProfileResponsePtr;
typedef boost::shared_ptr< ::ttl_driver::ReadVelocityProfileResponse const> ReadVelocityProfileResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator1> & lhs, const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator2> & rhs)
{
  return lhs.v_start == rhs.v_start &&
    lhs.a_1 == rhs.a_1 &&
    lhs.v_1 == rhs.v_1 &&
    lhs.a_max == rhs.a_max &&
    lhs.v_max == rhs.v_max &&
    lhs.d_max == rhs.d_max &&
    lhs.d_1 == rhs.d_1 &&
    lhs.v_stop == rhs.v_stop &&
    lhs.status == rhs.status &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator1> & lhs, const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ttl_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb1d3c27a4ecb4cb7ad1cd68d7179851";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb1d3c27a4ecb4cbULL;
  static const uint64_t static_value2 = 0x7ad1cd68d7179851ULL;
};

template<class ContainerAllocator>
struct DataType< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ttl_driver/ReadVelocityProfileResponse";
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 v_start\n"
"\n"
"float64 a_1\n"
"float64 v_1\n"
"\n"
"float64 a_max\n"
"float64 v_max\n"
"float64 d_max\n"
"\n"
"float64 d_1\n"
"\n"
"float64 v_stop\n"
"\n"
"int32 status\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.v_start);
      stream.next(m.a_1);
      stream.next(m.v_1);
      stream.next(m.a_max);
      stream.next(m.v_max);
      stream.next(m.d_max);
      stream.next(m.d_1);
      stream.next(m.v_stop);
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReadVelocityProfileResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ttl_driver::ReadVelocityProfileResponse_<ContainerAllocator>& v)
  {
    s << indent << "v_start: ";
    Printer<double>::stream(s, indent + "  ", v.v_start);
    s << indent << "a_1: ";
    Printer<double>::stream(s, indent + "  ", v.a_1);
    s << indent << "v_1: ";
    Printer<double>::stream(s, indent + "  ", v.v_1);
    s << indent << "a_max: ";
    Printer<double>::stream(s, indent + "  ", v.a_max);
    s << indent << "v_max: ";
    Printer<double>::stream(s, indent + "  ", v.v_max);
    s << indent << "d_max: ";
    Printer<double>::stream(s, indent + "  ", v.d_max);
    s << indent << "d_1: ";
    Printer<double>::stream(s, indent + "  ", v.d_1);
    s << indent << "v_stop: ";
    Printer<double>::stream(s, indent + "  ", v.v_stop);
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_READVELOCITYPROFILERESPONSE_H
