// Generated by gencpp from file ttl_driver/WriteVelocityProfile.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_WRITEVELOCITYPROFILE_H
#define TTL_DRIVER_MESSAGE_WRITEVELOCITYPROFILE_H

#include <ros/service_traits.h>


#include <ttl_driver/WriteVelocityProfileRequest.h>
#include <ttl_driver/WriteVelocityProfileResponse.h>


namespace ttl_driver
{

struct WriteVelocityProfile
{

typedef WriteVelocityProfileRequest Request;
typedef WriteVelocityProfileResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WriteVelocityProfile
} // namespace ttl_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ttl_driver::WriteVelocityProfile > {
  static const char* value()
  {
    return "0d7964b1831b6f9fe2e48dd363b22396";
  }

  static const char* value(const ::ttl_driver::WriteVelocityProfile&) { return value(); }
};

template<>
struct DataType< ::ttl_driver::WriteVelocityProfile > {
  static const char* value()
  {
    return "ttl_driver/WriteVelocityProfile";
  }

  static const char* value(const ::ttl_driver::WriteVelocityProfile&) { return value(); }
};


// service_traits::MD5Sum< ::ttl_driver::WriteVelocityProfileRequest> should match
// service_traits::MD5Sum< ::ttl_driver::WriteVelocityProfile >
template<>
struct MD5Sum< ::ttl_driver::WriteVelocityProfileRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ttl_driver::WriteVelocityProfile >::value();
  }
  static const char* value(const ::ttl_driver::WriteVelocityProfileRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ttl_driver::WriteVelocityProfileRequest> should match
// service_traits::DataType< ::ttl_driver::WriteVelocityProfile >
template<>
struct DataType< ::ttl_driver::WriteVelocityProfileRequest>
{
  static const char* value()
  {
    return DataType< ::ttl_driver::WriteVelocityProfile >::value();
  }
  static const char* value(const ::ttl_driver::WriteVelocityProfileRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ttl_driver::WriteVelocityProfileResponse> should match
// service_traits::MD5Sum< ::ttl_driver::WriteVelocityProfile >
template<>
struct MD5Sum< ::ttl_driver::WriteVelocityProfileResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ttl_driver::WriteVelocityProfile >::value();
  }
  static const char* value(const ::ttl_driver::WriteVelocityProfileResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ttl_driver::WriteVelocityProfileResponse> should match
// service_traits::DataType< ::ttl_driver::WriteVelocityProfile >
template<>
struct DataType< ::ttl_driver::WriteVelocityProfileResponse>
{
  static const char* value()
  {
    return DataType< ::ttl_driver::WriteVelocityProfile >::value();
  }
  static const char* value(const ::ttl_driver::WriteVelocityProfileResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_WRITEVELOCITYPROFILE_H
