// Generated by gencpp from file ttl_driver/WriteCustomValueResponse.msg
// DO NOT EDIT!


#ifndef TTL_DRIVER_MESSAGE_WRITECUSTOMVALUERESPONSE_H
#define TTL_DRIVER_MESSAGE_WRITECUSTOMVALUERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ttl_driver
{
template <class ContainerAllocator>
struct WriteCustomValueResponse_
{
  typedef WriteCustomValueResponse_<ContainerAllocator> Type;

  WriteCustomValueResponse_()
    : status(0)
    , message()  {
    }
  WriteCustomValueResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WriteCustomValueResponse_

typedef ::ttl_driver::WriteCustomValueResponse_<std::allocator<void> > WriteCustomValueResponse;

typedef boost::shared_ptr< ::ttl_driver::WriteCustomValueResponse > WriteCustomValueResponsePtr;
typedef boost::shared_ptr< ::ttl_driver::WriteCustomValueResponse const> WriteCustomValueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator1> & lhs, const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator1> & lhs, const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ttl_driver

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c1d00fb8b4e78420f43d93d5292a429";
  }

  static const char* value(const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c1d00fb8b4e7842ULL;
  static const uint64_t static_value2 = 0x0f43d93d5292a429ULL;
};

template<class ContainerAllocator>
struct DataType< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ttl_driver/WriteCustomValueResponse";
  }

  static const char* value(const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 status\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteCustomValueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ttl_driver::WriteCustomValueResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TTL_DRIVER_MESSAGE_WRITECUSTOMVALUERESPONSE_H
