// Generated by gencpp from file conveyor_interface/ControlConveyorResponse.msg
// DO NOT EDIT!


#ifndef CONVEYOR_INTERFACE_MESSAGE_CONTROLCONVEYORRESPONSE_H
#define CONVEYOR_INTERFACE_MESSAGE_CONTROLCONVEYORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace conveyor_interface
{
template <class ContainerAllocator>
struct ControlConveyorResponse_
{
  typedef ControlConveyorResponse_<ContainerAllocator> Type;

  ControlConveyorResponse_()
    : status(0)
    , message()  {
    }
  ControlConveyorResponse_(const ContainerAllocator& _alloc)
    : status(0)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlConveyorResponse_

typedef ::conveyor_interface::ControlConveyorResponse_<std::allocator<void> > ControlConveyorResponse;

typedef boost::shared_ptr< ::conveyor_interface::ControlConveyorResponse > ControlConveyorResponsePtr;
typedef boost::shared_ptr< ::conveyor_interface::ControlConveyorResponse const> ControlConveyorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator1> & lhs, const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator1> & lhs, const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace conveyor_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09803e1f4a40b6f2352e453a75b02d0b";
  }

  static const char* value(const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09803e1f4a40b6f2ULL;
  static const uint64_t static_value2 = 0x352e453a75b02d0bULL;
};

template<class ContainerAllocator>
struct DataType< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "conveyor_interface/ControlConveyorResponse";
  }

  static const char* value(const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 status\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlConveyorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::conveyor_interface::ControlConveyorResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int16_t>::stream(s, indent + "  ", v.status);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONVEYOR_INTERFACE_MESSAGE_CONTROLCONVEYORRESPONSE_H
