(cl:defpackage conveyor_interface-srv
  (:use )
  (:export
   "CONTROLCONVEYOR"
   "<CONTROLCONVEYOR-REQUEST>"
   "CONTROLCONVEYOR-REQUEST"
   "<CONTROLCONVEYOR-RESPONSE>"
   "CONTROLCONVEYOR-RESPONSE"
   "SETCONVEYOR"
   "<SETCONVEYOR-REQUEST>"
   "SETCONVEYOR-REQUEST"
   "<SETCONVEYOR-RESPONSE>"
   "SETCONVEYOR-RESPONSE"
  ))

