// Generated by gencpp from file niryo_robot_programs_manager/GetProgramRequest.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_GETPROGRAMREQUEST_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_GETPROGRAMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <niryo_robot_programs_manager/ProgramLanguage.h>

namespace niryo_robot_programs_manager
{
template <class ContainerAllocator>
struct GetProgramRequest_
{
  typedef GetProgramRequest_<ContainerAllocator> Type;

  GetProgramRequest_()
    : name()
    , language()  {
    }
  GetProgramRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , language(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef  ::niryo_robot_programs_manager::ProgramLanguage_<ContainerAllocator>  _language_type;
  _language_type language;





  typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetProgramRequest_

typedef ::niryo_robot_programs_manager::GetProgramRequest_<std::allocator<void> > GetProgramRequest;

typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramRequest > GetProgramRequestPtr;
typedef boost::shared_ptr< ::niryo_robot_programs_manager::GetProgramRequest const> GetProgramRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.language == rhs.language;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator1> & lhs, const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace niryo_robot_programs_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d82e409fb19e512ead16074d088a0fc";
  }

  static const char* value(const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d82e409fb19e512ULL;
  static const uint64_t static_value2 = 0xead16074d088a0fcULL;
};

template<class ContainerAllocator>
struct DataType< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "niryo_robot_programs_manager/GetProgramRequest";
  }

  static const char* value(const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"\n"
"niryo_robot_programs_manager/ProgramLanguage language\n"
"\n"
"================================================================================\n"
"MSG: niryo_robot_programs_manager/ProgramLanguage\n"
"int8 NONE = -1\n"
"\n"
"int8 ALL = 0\n"
"\n"
"# Runnable\n"
"int8 PYTHON2 = 1\n"
"int8 PYTHON3 = 2\n"
"\n"
"# Not Runnable\n"
"int8 BLOCKLY = 66\n"
"\n"
"int8 used\n"
;
  }

  static const char* value(const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.language);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetProgramRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::niryo_robot_programs_manager::GetProgramRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "language: ";
    s << std::endl;
    Printer< ::niryo_robot_programs_manager::ProgramLanguage_<ContainerAllocator> >::stream(s, indent + "  ", v.language);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_GETPROGRAMREQUEST_H
