// Generated by gencpp from file niryo_robot_programs_manager/SetProgramAutorun.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_SETPROGRAMAUTORUN_H
#define NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_SETPROGRAMAUTORUN_H

#include <ros/service_traits.h>


#include <niryo_robot_programs_manager/SetProgramAutorunRequest.h>
#include <niryo_robot_programs_manager/SetProgramAutorunResponse.h>


namespace niryo_robot_programs_manager
{

struct SetProgramAutorun
{

typedef SetProgramAutorunRequest Request;
typedef SetProgramAutorunResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetProgramAutorun
} // namespace niryo_robot_programs_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorun > {
  static const char* value()
  {
    return "6daf4f32083258273fc8b9bd84cd3a36";
  }

  static const char* value(const ::niryo_robot_programs_manager::SetProgramAutorun&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_programs_manager::SetProgramAutorun > {
  static const char* value()
  {
    return "niryo_robot_programs_manager/SetProgramAutorun";
  }

  static const char* value(const ::niryo_robot_programs_manager::SetProgramAutorun&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorunRequest> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorun >
template<>
struct MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorunRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager::SetProgramAutorunRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager::SetProgramAutorunRequest> should match
// service_traits::DataType< ::niryo_robot_programs_manager::SetProgramAutorun >
template<>
struct DataType< ::niryo_robot_programs_manager::SetProgramAutorunRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager::SetProgramAutorunRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorunResponse> should match
// service_traits::MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorun >
template<>
struct MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorunResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_programs_manager::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager::SetProgramAutorunResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_programs_manager::SetProgramAutorunResponse> should match
// service_traits::DataType< ::niryo_robot_programs_manager::SetProgramAutorun >
template<>
struct DataType< ::niryo_robot_programs_manager::SetProgramAutorunResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_programs_manager::SetProgramAutorun >::value();
  }
  static const char* value(const ::niryo_robot_programs_manager::SetProgramAutorunResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_PROGRAMS_MANAGER_MESSAGE_SETPROGRAMAUTORUN_H
