// Generated by gencpp from file niryo_robot_reports/CheckConnection.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_REPORTS_MESSAGE_CHECKCONNECTION_H
#define NIRYO_ROBOT_REPORTS_MESSAGE_CHECKCONNECTION_H

#include <ros/service_traits.h>


#include <niryo_robot_reports/CheckConnectionRequest.h>
#include <niryo_robot_reports/CheckConnectionResponse.h>


namespace niryo_robot_reports
{

struct CheckConnection
{

typedef CheckConnectionRequest Request;
typedef CheckConnectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckConnection
} // namespace niryo_robot_reports


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_reports::CheckConnection > {
  static const char* value()
  {
    return "601967d72fd39c22f6ae4773c148bd17";
  }

  static const char* value(const ::niryo_robot_reports::CheckConnection&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_reports::CheckConnection > {
  static const char* value()
  {
    return "niryo_robot_reports/CheckConnection";
  }

  static const char* value(const ::niryo_robot_reports::CheckConnection&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_reports::CheckConnectionRequest> should match
// service_traits::MD5Sum< ::niryo_robot_reports::CheckConnection >
template<>
struct MD5Sum< ::niryo_robot_reports::CheckConnectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_reports::CheckConnection >::value();
  }
  static const char* value(const ::niryo_robot_reports::CheckConnectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_reports::CheckConnectionRequest> should match
// service_traits::DataType< ::niryo_robot_reports::CheckConnection >
template<>
struct DataType< ::niryo_robot_reports::CheckConnectionRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_reports::CheckConnection >::value();
  }
  static const char* value(const ::niryo_robot_reports::CheckConnectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_reports::CheckConnectionResponse> should match
// service_traits::MD5Sum< ::niryo_robot_reports::CheckConnection >
template<>
struct MD5Sum< ::niryo_robot_reports::CheckConnectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_reports::CheckConnection >::value();
  }
  static const char* value(const ::niryo_robot_reports::CheckConnectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_reports::CheckConnectionResponse> should match
// service_traits::DataType< ::niryo_robot_reports::CheckConnection >
template<>
struct DataType< ::niryo_robot_reports::CheckConnectionResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_reports::CheckConnection >::value();
  }
  static const char* value(const ::niryo_robot_reports::CheckConnectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_REPORTS_MESSAGE_CHECKCONNECTION_H
