(cl:defpackage niryo_robot_sound-srv
  (:use )
  (:export
   "MANAGESOUND"
   "<MANAGESOUND-REQUEST>"
   "MANAGESOUND-REQUEST"
   "<MANAGESOUND-RESPONSE>"
   "MANAGESOUND-RESPONSE"
   "PLAYSOUND"
   "<PLAYSOUND-REQUEST>"
   "PLAYSOUND-REQUEST"
   "<PLAYSOUND-RESPONSE>"
   "PLAYSOUND-RESPONSE"
   "TEXTTOSPEECH"
   "<TEXTTOSPEECH-REQUEST>"
   "TEXTTOSPEECH-REQUEST"
   "<TEXTTOSPEECH-RESPONSE>"
   "TEXTTOSPEECH-RESPONSE"
  ))

