// Generated by gencpp from file niryo_robot_database/AddFilePath.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_DATABASE_MESSAGE_ADDFILEPATH_H
#define NIRYO_ROBOT_DATABASE_MESSAGE_ADDFILEPATH_H

#include <ros/service_traits.h>


#include <niryo_robot_database/AddFilePathRequest.h>
#include <niryo_robot_database/AddFilePathResponse.h>


namespace niryo_robot_database
{

struct AddFilePath
{

typedef AddFilePathRequest Request;
typedef AddFilePathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddFilePath
} // namespace niryo_robot_database


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_database::AddFilePath > {
  static const char* value()
  {
    return "9b37d66f02e489bae639ec70c5dd2e80";
  }

  static const char* value(const ::niryo_robot_database::AddFilePath&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_database::AddFilePath > {
  static const char* value()
  {
    return "niryo_robot_database/AddFilePath";
  }

  static const char* value(const ::niryo_robot_database::AddFilePath&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_database::AddFilePathRequest> should match
// service_traits::MD5Sum< ::niryo_robot_database::AddFilePath >
template<>
struct MD5Sum< ::niryo_robot_database::AddFilePathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_database::AddFilePath >::value();
  }
  static const char* value(const ::niryo_robot_database::AddFilePathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_database::AddFilePathRequest> should match
// service_traits::DataType< ::niryo_robot_database::AddFilePath >
template<>
struct DataType< ::niryo_robot_database::AddFilePathRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_database::AddFilePath >::value();
  }
  static const char* value(const ::niryo_robot_database::AddFilePathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_database::AddFilePathResponse> should match
// service_traits::MD5Sum< ::niryo_robot_database::AddFilePath >
template<>
struct MD5Sum< ::niryo_robot_database::AddFilePathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_database::AddFilePath >::value();
  }
  static const char* value(const ::niryo_robot_database::AddFilePathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_database::AddFilePathResponse> should match
// service_traits::DataType< ::niryo_robot_database::AddFilePath >
template<>
struct DataType< ::niryo_robot_database::AddFilePathResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_database::AddFilePath >::value();
  }
  static const char* value(const ::niryo_robot_database::AddFilePathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_DATABASE_MESSAGE_ADDFILEPATH_H
