// Generated by gencpp from file niryo_robot_sound/PlaySound.msg
// DO NOT EDIT!


#ifndef NIRYO_ROBOT_SOUND_MESSAGE_PLAYSOUND_H
#define NIRYO_ROBOT_SOUND_MESSAGE_PLAYSOUND_H

#include <ros/service_traits.h>


#include <niryo_robot_sound/PlaySoundRequest.h>
#include <niryo_robot_sound/PlaySoundResponse.h>


namespace niryo_robot_sound
{

struct PlaySound
{

typedef PlaySoundRequest Request;
typedef PlaySoundResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlaySound
} // namespace niryo_robot_sound


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::niryo_robot_sound::PlaySound > {
  static const char* value()
  {
    return "5ee90888968337d1f5c1d1a00df1090c";
  }

  static const char* value(const ::niryo_robot_sound::PlaySound&) { return value(); }
};

template<>
struct DataType< ::niryo_robot_sound::PlaySound > {
  static const char* value()
  {
    return "niryo_robot_sound/PlaySound";
  }

  static const char* value(const ::niryo_robot_sound::PlaySound&) { return value(); }
};


// service_traits::MD5Sum< ::niryo_robot_sound::PlaySoundRequest> should match
// service_traits::MD5Sum< ::niryo_robot_sound::PlaySound >
template<>
struct MD5Sum< ::niryo_robot_sound::PlaySoundRequest>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_sound::PlaySound >::value();
  }
  static const char* value(const ::niryo_robot_sound::PlaySoundRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_sound::PlaySoundRequest> should match
// service_traits::DataType< ::niryo_robot_sound::PlaySound >
template<>
struct DataType< ::niryo_robot_sound::PlaySoundRequest>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_sound::PlaySound >::value();
  }
  static const char* value(const ::niryo_robot_sound::PlaySoundRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::niryo_robot_sound::PlaySoundResponse> should match
// service_traits::MD5Sum< ::niryo_robot_sound::PlaySound >
template<>
struct MD5Sum< ::niryo_robot_sound::PlaySoundResponse>
{
  static const char* value()
  {
    return MD5Sum< ::niryo_robot_sound::PlaySound >::value();
  }
  static const char* value(const ::niryo_robot_sound::PlaySoundResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::niryo_robot_sound::PlaySoundResponse> should match
// service_traits::DataType< ::niryo_robot_sound::PlaySound >
template<>
struct DataType< ::niryo_robot_sound::PlaySoundResponse>
{
  static const char* value()
  {
    return DataType< ::niryo_robot_sound::PlaySound >::value();
  }
  static const char* value(const ::niryo_robot_sound::PlaySoundResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NIRYO_ROBOT_SOUND_MESSAGE_PLAYSOUND_H
